[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.build]
cmds = ["npm run build", "cp -r .output/public .output/server/chunks/public"]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NUXT_HOST = "0.0.0.0"
NUXT_PORT = "3000"
NITRO_HOST = "0.0.0.0"
NITRO_PORT = "3000"
NODE_ENV = "production"
NITRO_PRESET = "node-server"
NITRO_SERVE_STATIC = "true"
